/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jabaschool;

import static java.lang.Integer.parseInt;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author The_AK
 */
public class javaClass extends javax.swing.JFrame {

 private static final String username = "root";
 private static final String password = "";
 private static final String dbname = "jdbc:mysql://localhost:3306/jabaschool";
 private int id=0;
 
 Connection sqlConn = null;
 PreparedStatement pst = null;
 ResultSet rs = null;
 int q, i,deleteItem;
 
    
    public javaClass() {
        initComponents();
     try {
         upDateDB();
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(javaClass.class.getName()).log(Level.SEVERE, null, ex);
     }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    //===========================Function=======================
    
    public void upDateDB() throws ClassNotFoundException{
        
                try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dbname,username,password);
            pst = sqlConn.prepareStatement("select * from jabaclass");
            
            rs = pst.executeQuery();
            
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel maTable = (DefaultTableModel)tblEtudiant.getModel();
            maTable.setRowCount(0);
            
            while(rs.next()){
                
                Vector dataColn = new Vector();
                
                for(i=1;i<=q;i++){
                    
                    dataColn.add(rs.getInt("id"));
                    dataColn.add(rs.getString("Matricule"));
                    dataColn.add(rs.getString("Nom"));
                    dataColn.add(rs.getString("Prenom"));
                    dataColn.add(rs.getString("Adresse"));
                    dataColn.add(rs.getString("BoitePostal"));
                    dataColn.add(rs.getString("Telephone"));
                }
                maTable.addRow(dataColn);
            
            }    
        
        }catch(SQLException ex){
            
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    //=======================End Function===============
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        formPane = new javax.swing.JPanel();
        txtMatricule = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        txtPB = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField61 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEtudiant = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnAjouter = new javax.swing.JButton();
        btnModif = new javax.swing.JButton();
        btnSup = new javax.swing.JButton();
        btnAfficher = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        btnSortir = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 168), 6, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 168), 6, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 168), 6, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 240, 370));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 240, 370));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 168), 6, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 168), 6, true));
        formPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMatricule.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        formPane.add(txtMatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 450, 50));

        jTextField4.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField4.setText("jTextField1");
        formPane.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 450, 50));

        jTextField5.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField5.setText("jTextField1");
        formPane.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 450, 50));

        jTextField3.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField3.setText("jTextField1");
        formPane.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 450, 50));

        jLabel5.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jLabel5.setText("Matricule :");
        formPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 170, 50));

        jTextField6.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField6.setText("jTextField1");
        formPane.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 450, 50));

        jTextField9.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField9.setText("jTextField1");
        formPane.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 450, 50));

        txtNom.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        formPane.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 450, 50));

        jTextField13.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField13.setText("jTextField1");
        formPane.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 450, 50));

        jTextField14.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField14.setText("jTextField1");
        formPane.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 450, 50));

        jTextField17.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField17.setText("jTextField1");
        formPane.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 450, 50));

        jLabel7.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jLabel7.setText("Nom :");
        formPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 80, 50));

        jTextField18.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField18.setText("jTextField1");
        formPane.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 450, 50));

        jTextField19.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField19.setText("jTextField1");
        formPane.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 450, 50));

        txtPrenom.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        formPane.add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 450, 50));

        jTextField23.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField23.setText("jTextField1");
        formPane.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 450, 50));

        jTextField24.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField24.setText("jTextField1");
        formPane.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 450, 50));

        jTextField27.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField27.setText("jTextField1");
        formPane.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 450, 50));

        jLabel9.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jLabel9.setText("Prenom :");
        formPane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 120, 50));

        jTextField28.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField28.setText("jTextField1");
        formPane.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 450, 50));

        jTextField29.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField29.setText("jTextField1");
        formPane.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 450, 50));

        txtAdress.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        formPane.add(txtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 450, 50));

        jTextField33.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField33.setText("jTextField1");
        formPane.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 450, 50));

        jTextField34.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField34.setText("jTextField1");
        formPane.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 450, 50));

        jTextField37.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField37.setText("jTextField1");
        formPane.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 450, 50));

        jLabel11.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jLabel11.setText("Adress :");
        formPane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 120, 50));

        jTextField38.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField38.setText("jTextField1");
        formPane.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 450, 50));

        jTextField39.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField39.setText("jTextField1");
        formPane.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 450, 50));

        txtPB.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        formPane.add(txtPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 450, 50));

        jTextField43.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField43.setText("jTextField1");
        formPane.add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 450, 50));

        jTextField44.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField44.setText("jTextField1");
        formPane.add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 450, 50));

        jTextField47.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField47.setText("jTextField1");
        formPane.add(jTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 450, 50));

        jLabel13.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jLabel13.setText("PO Box :");
        formPane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 120, 50));

        jTextField48.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField48.setText("jTextField1");
        formPane.add(jTextField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 450, 50));

        jTextField49.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField49.setText("jTextField1");
        formPane.add(jTextField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 450, 50));

        txtTelephone.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        formPane.add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 450, 50));

        jTextField53.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField53.setText("jTextField1");
        formPane.add(jTextField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 450, 50));

        jTextField54.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField54.setText("jTextField1");
        formPane.add(jTextField54, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 450, 50));

        jTextField55.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField55.setText("jTextField1");
        formPane.add(jTextField55, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 450, 50));

        jTextField60.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField60.setText("jTextField1");
        formPane.add(jTextField60, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 450, 50));

        jLabel15.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jLabel15.setText("Telephone :");
        formPane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 170, 50));

        jTextField61.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jTextField61.setText("jTextField1");
        formPane.add(jTextField61, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 450, 50));

        tblEtudiant.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        tblEtudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Matricule", "Nom", "Prenom", "Adresse", "PO Box", "Telephone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEtudiant.setRowHeight(30);
        tblEtudiant.setShowGrid(false);
        tblEtudiant.setShowHorizontalLines(true);
        tblEtudiant.getTableHeader().setResizingAllowed(false);
        tblEtudiant.getTableHeader().setReorderingAllowed(false);
        tblEtudiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEtudiantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEtudiant);

        jScrollPane2.setViewportView(jScrollPane1);

        formPane.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 940, 210));

        jPanel1.add(formPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 960, 680));

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 168), 6, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 168), 6, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 168), 6, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 168), 6, true));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 240, 370));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 240, 370));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 240, 370));

        btnAjouter.setBackground(new java.awt.Color(63, 242, 75));
        btnAjouter.setFont(new java.awt.Font("Heebo", 1, 18)); // NOI18N
        btnAjouter.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouter.setText("AJOUTER");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        jPanel6.add(btnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, 70));

        btnModif.setBackground(new java.awt.Color(0, 255, 204));
        btnModif.setFont(new java.awt.Font("Heebo", 1, 18)); // NOI18N
        btnModif.setForeground(new java.awt.Color(255, 255, 255));
        btnModif.setText("MODIFIER");
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });
        jPanel6.add(btnModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, 70));

        btnSup.setBackground(new java.awt.Color(246, 14, 14));
        btnSup.setFont(new java.awt.Font("Heebo", 1, 18)); // NOI18N
        btnSup.setText("SUPPRIMER");
        btnSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupActionPerformed(evt);
            }
        });
        jPanel6.add(btnSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 210, 70));

        btnAfficher.setBackground(new java.awt.Color(10, 10, 243));
        btnAfficher.setFont(new java.awt.Font("Heebo", 1, 18)); // NOI18N
        btnAfficher.setForeground(new java.awt.Color(255, 255, 255));
        btnAfficher.setText("IMPRIMER");
        btnAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficherActionPerformed(evt);
            }
        });
        jPanel6.add(btnAfficher, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 210, 70));

        btnAnnuler.setBackground(new java.awt.Color(153, 0, 0));
        btnAnnuler.setFont(new java.awt.Font("Heebo", 1, 18)); // NOI18N
        btnAnnuler.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnuler.setText("ANNULER");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });
        jPanel6.add(btnAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 210, 70));

        btnSortir.setBackground(new java.awt.Color(0, 0, 0));
        btnSortir.setFont(new java.awt.Font("Heebo", 1, 18)); // NOI18N
        btnSortir.setForeground(new java.awt.Color(255, 255, 255));
        btnSortir.setText("SORTIR");
        btnSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortirActionPerformed(evt);
            }
        });
        jPanel6.add(btnSortir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 210, 70));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 110, 260, 690));

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("😁😁😁MYSQL JAVA MYSQL😁😁😁");
        jPanel11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 680, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1240, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1260, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private JFrame frame;
    private void btnSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortirActionPerformed
        
         frame = new JFrame("Exit");
         
         if(JOptionPane.showConfirmDialog(frame,"Voulez vous vraiment sortir??","Jaba School",
                 JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
             
             System.exit(0);
             
         }
    }//GEN-LAST:event_btnSortirActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        
        txtMatricule.setText("");
        txtNom.setText("");
        txtPrenom.setText("");
        txtAdress.setText("");
        txtPB.setText("");
        txtTelephone.setText("");
              
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        
        String Matricule = txtMatricule.getText();
        String Nom = txtNom.getText();
        String Prenom = txtPrenom.getText();
        String Adress = txtAdress.getText();
        String BP = txtPB.getText();
        String Telephone = txtTelephone.getText();
        
        if((Matricule.equals(""))||(Nom.equals(""))||(Prenom.equals(""))||(Adress.equals(""))||(BP.equals(""))||(Telephone.equals(""))){
            
            JOptionPane.showMessageDialog(this, "Remplissez tout les champs");     
        }else{
            
       try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dbname,username,password);
            pst = sqlConn.prepareStatement("insert into jabaclass(Matricule, Nom, Prenom, Adresse, BoitePostal, Telephone) values(?,?,?,?,?,?)");
            
            pst.setString(1,Matricule);
            pst.setString(2,Nom);
            pst.setString(3,Prenom);
            pst.setString(4,Adress);
            pst.setString(5,BP);
            pst.setString(6,Telephone);
            
            pst.executeUpdate();
            
        txtMatricule.setText("");
        txtNom.setText("");
        txtPrenom.setText("");
        txtAdress.setText("");
        txtPB.setText("");
        txtTelephone.setText("");
        
        upDateDB();
            
            
            
            JOptionPane.showMessageDialog(this,"Etudiant Enregistrer");
            
        }   catch (SQLException ex) { 
                Logger.getLogger(javaClass.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(javaClass.class.getName()).log(Level.SEVERE, null, ex);
            }  
        
        
        
        
        
        }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
      
        String Matricule = txtMatricule.getText();
        String Nom = txtNom.getText();
        String Prenom = txtPrenom.getText();
        String Adress = txtAdress.getText();
        String BP = txtPB.getText();
        String Telephone = txtTelephone.getText();
        
        if((Matricule.equals(""))||(Nom.equals(""))||(Prenom.equals(""))||(Adress.equals(""))||(BP.equals(""))||(Telephone.equals(""))){
            
            JOptionPane.showMessageDialog(this, "Remplissez tout les champs");     
        }else{
            
       try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dbname,username,password);
            pst = sqlConn.prepareStatement("update jabaclass set Matricule=?, Nom=?, Prenom=?, Adresse=?,BoitePostal=?,Telephone=? where id=?");
            
            pst.setString(1,Matricule);
            pst.setString(2,Nom);
            pst.setString(3,Prenom);
            pst.setString(4,Adress);
            pst.setString(5,BP);
            pst.setString(6,Telephone);
            pst.setString(7,Integer.toString(id));
            
            pst.executeUpdate();
            
        txtMatricule.setText("");
        txtNom.setText("");
        txtPrenom.setText("");
        txtAdress.setText("");
        txtPB.setText("");
        txtTelephone.setText("");
        
        upDateDB();
            
            
            
            JOptionPane.showMessageDialog(this,"Etudiant Modifier");
            
        }   catch (SQLException ex) { 
                Logger.getLogger(javaClass.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(javaClass.class.getName()).log(Level.SEVERE, null, ex);
            }  
        
        
        
        
        
        }
    }//GEN-LAST:event_btnModifActionPerformed

    private void tblEtudiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEtudiantMouseClicked
        
            DefaultTableModel maTable = (DefaultTableModel)tblEtudiant.getModel();
            int selectedRows = tblEtudiant.getSelectedRow();
            
            id = parseInt(maTable.getValueAt(selectedRows, 0).toString());
            txtMatricule.setText(maTable.getValueAt(selectedRows, 1).toString());
            txtNom.setText(maTable.getValueAt(selectedRows, 2).toString());
            txtPrenom.setText(maTable.getValueAt(selectedRows, 3).toString());
            txtAdress.setText(maTable.getValueAt(selectedRows, 4).toString());
            txtPB.setText(maTable.getValueAt(selectedRows, 5).toString());
            txtTelephone.setText(maTable.getValueAt(selectedRows, 6).toString());
            
    }//GEN-LAST:event_tblEtudiantMouseClicked

    private void btnAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfficherActionPerformed
        
        MessageFormat header = new MessageFormat("Impression en cours");
        MessageFormat footer = new MessageFormat("Page {0, number, interger}");
      
        try{
            tblEtudiant.print(JTable.PrintMode.NORMAL,header,footer);
        }catch(java.awt.print.PrinterException e){
            
            System.err.format("Aucune imprimante brancher",e.getMessage());
        }
    }//GEN-LAST:event_btnAfficherActionPerformed

    private void btnSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupActionPerformed
        

        
        if(id==1){
            
            JOptionPane.showMessageDialog(this, "Remplissez tout les champs");     
        }else{
            
       try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dbname,username,password);
            pst = sqlConn.prepareStatement("delete from jabaclass where id=?");
            
            pst.setString(1,Integer.toString(id));
            
            pst.executeUpdate();
            
        txtMatricule.setText("");
        txtNom.setText("");
        txtPrenom.setText("");
        txtAdress.setText("");
        txtPB.setText("");
        txtTelephone.setText("");
            
            
            
            JOptionPane.showMessageDialog(this,"Etudiant Supprimer");
            
        }   catch (SQLException ex) { 
                Logger.getLogger(javaClass.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(javaClass.class.getName()).log(Level.SEVERE, null, ex);
            }  
        
        
        
        
        
        } 
        
        
        
    }//GEN-LAST:event_btnSupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(javaClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(javaClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(javaClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(javaClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new javaClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfficher;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnModif;
    private javax.swing.JButton btnSortir;
    private javax.swing.JButton btnSup;
    private javax.swing.JPanel formPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tblEtudiant;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtMatricule;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPB;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
